set ( RECLUSE_WXWIDGETS_INCLUDE_DIR ${RECLUSE_THIRDPARTY_DIR}/wxWidgets/include )

set ( RECLUSE_EDITOR_INCLUDE_FILES ${RECLUSE_EDITOR_INCLUDE_FILES} 
		${RECLUSE_WXWIDGETS_INCLUDE_DIR}
	)

set ( RECLUSE_EDITOR_COMPILE_FILES ${RECLUSE_EDITOR_COMPILE_FILES}
	${RECLUSE_EDITOR_SOURCE_DIR}/main.cpp
	
	)