set ( RECLUSE_EDITOR_WXWIDGETS_DIR ${RECLUSE_EDITOR_SOURCE_DIR}/WxWidgets )
set ( RECLUSE_EDITOR_GEOMETRY_INCLUDE_DIR ${RECLUSE_EDITOR_INCLUDE_DIR}/Geometry )
set ( RECLUSE_EDITOR_GEOMETRY_SOURCE_DIR ${RECLUSE_EDITOR_SOURCE_DIR}/Geometry )

set ( RECLUSE_EDITOR_COMPILE_FILES ${RECLUSE_EDITOR_COMPILE_FILES}
	${RECLUSE_EDITOR_SOURCE_DIR}/main.cpp
	${RECLUSE_EDITOR_SOURCE_DIR}/MainEditorFrame.cpp
	${RECLUSE_EDITOR_INCLUDE_DIR}/MainEditorFrame.hpp
	${RECLUSE_EDITOR_SOURCE_DIR}/GUIFactory.hpp
	${RECLUSE_EDITOR_SOURCE_DIR}/GUIFactory.cpp
	${RECLUSE_EDITOR_INCLUDE_DIR}/GUIContext.hpp
	${RECLUSE_EDITOR_GEOMETRY_INCLUDE_DIR}/Cube.hpp
	${RECLUSE_EDITOR_GEOMETRY_INCLUDE_DIR}/Sphere.hpp
	${RECLUSE_EDITOR_GEOMETRY_SOURCE_DIR}/Cube.cpp
	${RECLUSE_EDITOR_GEOMETRY_SOURCE_DIR}/Sphere.cpp
	)
	
	
if (NOT WXWIDGETS_DISABLE)
	set ( RECLUSE_WXWIDGETS_INCLUDE_DIR ${RECLUSE_INCLUDE_DIRECTORY} ${RECLUSE_INCLUDE_DIRECTORY}/msvc )
	
	set ( RECLUSE_EDITOR_INCLUDE_FILES ${RECLUSE_EDITOR_INCLUDE_FILES} 
		${RECLUSE_WXWIDGETS_INCLUDE_DIR}
	)

	set(wxWidgets_ROOT_DIR ${CMAKE_INSTALL_PREFIX})
	set(wxWidgets_LIB_DIR ${CMAKE_INSTALL_PREFIX}/lib/vc_x64_dll)
	set(wxWidgets_CONFIGURATION mswu)
	find_package(wxWidgets REQUIRED COMPONENTS net core base)


	file(GLOB_RECURSE WX_DLLS "${CMAKE_INSTALL_PREFIX}/lib/vc_x64_dll/*.dll")
	foreach(_FILE ${WX_DLLS})
		file(INSTALL
			DESTINATION ${CMAKE_INSTALL_PREFIX}/Bin
			TYPE SHARED_LIBRARY
			FOLLOW_SYMLINK_CHAIN
			FILES "${_FILE}"
		)
	endforeach()

	set ( RECLUSE_EDITOR_COMPILE_FILES
		${RECLUSE_EDITOR_COMPILE_FILES}
		${RECLUSE_EDITOR_WXWIDGETS_DIR}/WxContext.hpp
		${RECLUSE_EDITOR_WXWIDGETS_DIR}/WxFrame.hpp
		${RECLUSE_EDITOR_WXWIDGETS_DIR}/WxContext.cpp
		${RECLUSE_EDITOR_SOURCE_DIR}/Renderer.hpp
		${RECLUSE_EDITOR_SOURCE_DIR}/Renderer.cpp
	)
	
	add_definitions(-DUNICODE)
	add_definitions(-D_UNICODE)

	set (RECLUSE_EDITOR_LINK_BINARIES ${RECLUSE_EDITOR_LINK_BINARIES}  ${wxWidgets_LIBRARIES})
endif()