set ( RECLUSE_WXWIDGETS_INCLUDE_DIR ${RECLUSE_THIRDPARTY_DIR}/wxWidgets/include )

set ( RECLUSE_EDITOR_INCLUDE_FILES ${RECLUSE_EDITOR_INCLUDE_FILES} 
		${RECLUSE_WXWIDGETS_INCLUDE_DIR}
	)
	
	
set ( RECLUSE_EDITOR_WXWIDGETS_DIR ${RECLUSE_EDITOR_SOURCE_DIR}/WxWidgets )
set ( RECLUSE_EDITOR_GEOMETRY_INCLUDE_DIR ${RECLUSE_EDITOR_INCLUDE_DIR}/Geometry )
set ( RECLUSE_EDITOR_GEOMETRY_SOURCE_DIR ${RECLUSE_EDITOR_SOURCE_DIR}/Geometry )

set ( RECLUSE_EDITOR_COMPILE_FILES ${RECLUSE_EDITOR_COMPILE_FILES}
	${RECLUSE_EDITOR_SOURCE_DIR}/main.cpp
	${RECLUSE_EDITOR_SOURCE_DIR}/MainEditorFrame.cpp
	${RECLUSE_EDITOR_INCLUDE_DIR}/MainEditorFrame.hpp
	${RECLUSE_EDITOR_SOURCE_DIR}/GUIFactory.hpp
	${RECLUSE_EDITOR_SOURCE_DIR}/GUIFactory.cpp
	${RECLUSE_EDITOR_INCLUDE_DIR}/GUIContext.hpp
	${RECLUSE_EDITOR_GEOMETRY_INCLUDE_DIR}/Cube.hpp
	${RECLUSE_EDITOR_GEOMETRY_INCLUDE_DIR}/Sphere.hpp
	${RECLUSE_EDITOR_GEOMETRY_SOURCE_DIR}/Cube.cpp
	${RECLUSE_EDITOR_GEOMETRY_SOURCE_DIR}/Sphere.cpp
	)
	
	
if (NOT WXWIDGETS_DISABLE)
set ( RECLUSE_EDITOR_COMPILE_FILES
	${RECLUSE_EDITOR_COMPILE_FILES}
	${RECLUSE_EDITOR_WXWIDGETS_DIR}/WxContext.hpp
	${RECLUSE_EDITOR_WXWIDGETS_DIR}/WxFrame.hpp
	${RECLUSE_EDITOR_WXWIDGETS_DIR}/WxContext.cpp
	${RECLUSE_EDITOR_SOURCE_DIR}/Renderer.hpp
	${RECLUSE_EDITOR_SOURCE_DIR}/Renderer.cpp
)
endif()