//
#pragma once

#include "Recluse/Types.hpp"

namespace Recluse {

enum ResourceFormat {
    RESOURCE_FORMAT_R8G8B8A8_UNORM,
    RESOURCE_FORMAT_R16G16B16A16_FLOAT,
    RESOURCE_FORMAT_R11G11B10_FLOAT,
    RESOURCE_FORMAT_D32_FLOAT,
    RESOURCE_FORMAT_R32_FLOAT,
    RESOURCE_FORMAT_D24_UNORM_S8_UINT,
    RESOURCE_FORMAT_R16G16_FLOAT,
    RESOURCE_FORMAT_B8G8R8A8_SRGB,
    RESOURCE_FORMAT_R32G32B32A32_FLOAT,
    RESOURCE_FORMAT_R32G32B32A32_UINT,
    RESOURCE_FORMAT_R8_UINT,
    RESOURCE_FORMAT_R32G32_FLOAT,
    RESOURCE_FORMAT_R32G32_UINT,
    RESOURCE_FORMAT_R16_UINT,
    RESOURCE_FORMAT_R16_FLOAT
};
} // Recluse