set ( RECLUSE_PIPE_INCLUDE ${RECLUSE_PIPELINE_INCLUDE}/Recluse/Pipeline )
set ( RECLUSE_PIPE_SOURCE ${RECLUSE_PIPELINE_SOURCE})


set (RECLUSE_PIPELINE_INCLUDE_FILES ${RECLUSE_PIPELINE_INCLUDE_FILES}
									${RECLUSE_PIPE_INCLUDE}/ShaderProgramBuilder.hpp)
									
set(RECLUSE_PIPELINE_COMPILE_FILES ${RECLUSE_PIPELINE_COMPILE_FILES}
								  ${RECLUSE_PIPELINE_INCLUDE_FILES}
								  ${RECLUSE_PIPE_SOURCE}/ShaderProgramBuilder.cpp)