#
set ( RECLUSE_ENGINE_ANIMATION_INCLUDE ${RECLUSE_ENGINE_INCLUDE_DIR}/Recluse/Animation )
set ( RECLUSE_ENGINE_ANIMATION_SOURCE ${RECLUSE_ENGINE_SOURCE_DIR}/Animation )

set (RECLUSE_ENGINE_COMPILE_FILES
	${RECLUSE_ENGINE_COMPILE_FILES}
	${RECLUSE_ENGINE_ANIMATION_INCLUDE}/Animation.hpp
	${RECLUSE_ENGINE_ANIMATION_INCLUDE}/AnimationInterp.hpp
	${RECLUSE_ENGINE_ANIMATION_INCLUDE}/Blend.hpp
	${RECLUSE_ENGINE_ANIMATION_INCLUDE}/Clip.hpp
	${RECLUSE_ENGINE_ANIMATION_INCLUDE}/Joint.hpp
	${RECLUSE_ENGINE_ANIMATION_INCLUDE}/Skeleton.hpp
	${RECLUSE_ENGINE_ANIMATION_SOURCE}/Animation.cpp
)