#
set ( RECLUSE_ENGINE_CORE_INCLUDE ${RECLUSE_ENGINE_INCLUDE_DIR}/Recluse/Core)
set ( RECLUSE_ENGINE_CORE_SOURCE ${RECLUSE_ENGINE_SOURCE_DIR}/Core )

set ( RECLUSE_ENGINE_PROFILE_INCLUDE ${RECLUSE_ENGINE_INCLUDE_DIR}/Recluse/Core/Profile )
set ( RECLUSE_ENGINE_PROFILE_SOURCE ${RECLUSE_ENGINE_SOURCE_DIR}/Core/Profile )


set ( RECLUSE_ENGINE_COMPILE_FILES 
	${RECLUSE_ENGINE_COMPILE_FILES}
	${RECLUSE_ENGINE_PROFILE_INCLUDE}/Profiler.hpp
	${RECLUSE_ENGINE_PROFILE_SOURCE}/Profiler.cpp
	${RECLUSE_ENGINE_PROFILE_SOURCE}/ProfilerManager.hpp
	${RECLUSE_ENGINE_PROFILE_SOURCE}/ProfilerManager.cpp
)