set ( RECLUSE_ENGINE_SCENE_INCLUDE_DIR ${RECLUSE_ENGINE_INCLUDE_DIR}/Recluse/Scene )
set ( RECLUSE_ENGINE_SCENE_SOURCE_DIR ${RECLUSE_ENGINE_SOURCE_DIR}/Scene )

set ( RECLUSE_ENGINE_COMPILE_FILES
    ${RECLUSE_ENGINE_COMPILE_FILES}
    ${RECLUSE_ENGINE_SCENE_INCLUDE_DIR}/Scene.hpp
    ${RECLUSE_ENGINE_SCENE_INCLUDE_DIR}/SceneLoader.hpp
    ${RECLUSE_ENGINE_SCENE_INCLUDE_DIR}/SerializeManager.hpp
	${RECLUSE_ENGINE_SCENE_INCLUDE_DIR}/Camera.hpp
    ${RECLUSE_ENGINE_SCENE_SOURCE_DIR}/Scene.cpp
	${RECLUSE_ENGINE_SCENE_SOURCE_DIR}/Camera.cpp
)